spring:
    application:
        name: gateway
    cloud:
      gateway:
        routes:
          - id: patient-module-swagger
            uri: lb://patient-module
            predicates:
              - Path=/swagger-ui/**, /v3/api-docs/**, /swagger-resources/**, /webjars/**
          - id: patient-module
            uri: lb://patient-module
            predicates:
              - Path=/patient/**, /history-medical/**
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
